addSbtPlugin("org.scalameta"         % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("com.lightbend.paradox" % "sbt-paradox"         % "0.9.2")
addSbtPlugin("com.github.sbt"        % "sbt-native-packager" % "1.9.8")
addSbtPlugin("com.codecommit"        % "sbt-github-actions"  % "0.14.2")
addSbtPlugin("com.github.sbt"        % "sbt-pgp"             % "2.1.2")
addSbtPlugin("com.github.sbt"        % "sbt-release"         % "1.1.0")
addSbtPlugin("ch.epfl.scala"         % "sbt-scalafix"        % "0.9.34")
