addSbtPlugin("org.scalameta"         % "sbt-scalafmt"        % "2.4.3")
addSbtPlugin("com.lightbend.paradox" % "sbt-paradox"         % "0.9.2")
addSbtPlugin("com.typesafe.sbt"      % "sbt-native-packager" % "1.8.1")
addSbtPlugin("com.codecommit"        % "sbt-github-actions"  % "0.12.0")
addSbtPlugin("com.github.sbt"        % "sbt-pgp"             % "2.1.2")
addSbtPlugin("com.github.sbt"        % "sbt-release"         % "1.1.0")
