name: Update Dependency Graph
on:
  push:
    branches:
      - main # default branch of the project
permissions:
  contents: write
jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: scalacenter/sbt-dependency-submission@v2
